param sites_poc_refinity_invoicing_func_name string = 'poc-refinity-invoicing-func'
param serverfarms_ASP_CAFunctionAppFlexPOC_bb59_externalid string = '/subscriptions/883433d1-c6a4-4cd3-9d39-567702e61f18/resourceGroups/CA-FunctionApp-Flex-POC/providers/Microsoft.Web/serverfarms/ASP-CAFunctionAppFlexPOC-bb59'
param virtualNetworks_CA_Application_externalid string = '/subscriptions/883433d1-c6a4-4cd3-9d39-567702e61f18/resourceGroups/CCI-Global-Network/providers/Microsoft.Network/virtualNetworks/CA-Application'

resource sites_poc_refinity_invoicing_func_name_resource 'Microsoft.Web/sites@2024-11-01' = {
  name: sites_poc_refinity_invoicing_func_name
  location: 'Canada Central'
  kind: 'functionapp,linux'
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '/subscriptions/883433d1-c6a4-4cd3-9d39-567702e61f18/resourcegroups/CA-FunctionApp-Flex-POC/providers/Microsoft.ManagedIdentity/userAssignedIdentities/poc-akzo-invoicing-mi': {}
    }
  }
  properties: {
    enabled: true
    hostNameSslStates: [
      {
        name: '${sites_poc_refinity_invoicing_func_name}-hzb7htdfdvfwgbfc.canadacentral-01.azurewebsites.net'
        sslState: 'Disabled'
        hostType: 'Standard'
      }
      {
        name: '${sites_poc_refinity_invoicing_func_name}-hzb7htdfdvfwgbfc.scm.canadacentral-01.azurewebsites.net'
        sslState: 'Disabled'
        hostType: 'Repository'
      }
    ]
    serverFarmId: serverfarms_ASP_CAFunctionAppFlexPOC_bb59_externalid
    reserved: true
    isXenon: false
    hyperV: false
    dnsConfiguration: {}
    outboundVnetRouting: {
      allTraffic: false
      applicationTraffic: false
      contentShareTraffic: false
      imagePullTraffic: false
      backupRestoreTraffic: false
    }
    siteConfig: {
      numberOfWorkers: 1
      acrUseManagedIdentityCreds: false
      alwaysOn: false
      http20Enabled: false
      functionAppScaleLimit: 100
      minimumElasticInstanceCount: 0
    }
    functionAppConfig: {
      deployment: {
        storage: {
          type: 'blobcontainer'
          value: 'https://cafunctionappflexpoa5cb.blob.core.windows.net/app-package-${sites_poc_refinity_invoicing_func_name}-78b79df'
          authentication: {
            type: 'storageaccountconnectionstring'
            storageAccountConnectionStringName: 'DEPLOYMENT_STORAGE_CONNECTION_STRING'
          }
        }
      }
      runtime: {
        name: 'dotnet-isolated'
        version: '9.0'
      }
      scaleAndConcurrency: {
        maximumInstanceCount: 100
        instanceMemoryMB: 2048
      }
    }
    scmSiteAlsoStopped: false
    clientAffinityEnabled: false
    clientAffinityProxyEnabled: false
    clientCertEnabled: false
    clientCertMode: 'Required'
    hostNamesDisabled: false
    ipMode: 'IPv4'
    customDomainVerificationId: '8C67BCEB125346BECD1B4F6858172AEDA8DE35DF6140D4CC81C373200A940D67'
    containerSize: 1536
    dailyMemoryTimeQuota: 0
    httpsOnly: true
    endToEndEncryptionEnabled: false
    redundancyMode: 'None'
    publicNetworkAccess: 'Disabled'
    storageAccountRequired: false
    virtualNetworkSubnetId: '${virtualNetworks_CA_Application_externalid}/subnets/Dev-FunctionApp-Flex-Outbound'
    keyVaultReferenceIdentity: 'SystemAssigned'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
  }
}

resource sites_poc_refinity_invoicing_func_name_ftp 'Microsoft.Web/sites/basicPublishingCredentialsPolicies@2024-11-01' = {
  parent: sites_poc_refinity_invoicing_func_name_resource
  name: 'ftp'
  location: 'Canada Central'
  properties: {
    allow: false
  }
}

resource sites_poc_refinity_invoicing_func_name_scm 'Microsoft.Web/sites/basicPublishingCredentialsPolicies@2024-11-01' = {
  parent: sites_poc_refinity_invoicing_func_name_resource
  name: 'scm'
  location: 'Canada Central'
  properties: {
    allow: false
  }
}

resource sites_poc_refinity_invoicing_func_name_web 'Microsoft.Web/sites/config@2024-11-01' = {
  parent: sites_poc_refinity_invoicing_func_name_resource
  name: 'web'
  location: 'Canada Central'
  properties: {
    numberOfWorkers: 1
    defaultDocuments: [
      'Default.htm'
      'Default.html'
      'Default.asp'
      'index.htm'
      'index.html'
      'iisstart.htm'
      'default.aspx'
      'index.php'
    ]
    netFrameworkVersion: 'v4.0'
    requestTracingEnabled: false
    remoteDebuggingEnabled: false
    httpLoggingEnabled: false
    acrUseManagedIdentityCreds: false
    logsDirectorySizeLimit: 35
    detailedErrorLoggingEnabled: false
    publishingUsername: 'REDACTED'
    scmType: 'None'
    use32BitWorkerProcess: false
    webSocketsEnabled: false
    alwaysOn: false
    managedPipelineMode: 'Integrated'
    virtualApplications: [
      {
        virtualPath: '/'
        physicalPath: 'site\\wwwroot'
        preloadEnabled: false
      }
    ]
    loadBalancing: 'LeastRequests'
    experiments: {
      rampUpRules: []
    }
    autoHealEnabled: false
    vnetName: 'b5bfcd3b-3929-4b8c-a4e5-08b9f380fe75_Dev-FunctionApp-Flex-Outbound'
    vnetRouteAllEnabled: false
    vnetPrivatePortsCount: 0
    publicNetworkAccess: 'Disabled'
    cors: {
      allowedOrigins: [
        'https://portal.azure.com'
      ]
      supportCredentials: false
    }
    localMySqlEnabled: false
    xManagedServiceIdentityId: 12029
    ipSecurityRestrictions: [
      {
        ipAddress: 'Any'
        action: 'Allow'
        priority: 2147483647
        name: 'Allow all'
        description: 'Allow all access'
      }
    ]
    ipSecurityRestrictionsDefaultAction: 'Allow'
    scmIpSecurityRestrictions: [
      {
        ipAddress: 'Any'
        action: 'Allow'
        priority: 2147483647
        name: 'Allow all'
        description: 'Allow all access'
      }
    ]
    scmIpSecurityRestrictionsDefaultAction: 'Allow'
    scmIpSecurityRestrictionsUseMain: false
    http20Enabled: false
    minTlsVersion: '1.2'
    scmMinTlsVersion: '1.2'
    ftpsState: 'FtpsOnly'
    preWarmedInstanceCount: 0
    functionAppScaleLimit: 100
    functionsRuntimeScaleMonitoringEnabled: false
    minimumElasticInstanceCount: 0
    azureStorageAccounts: {}
    http20ProxyFlag: 0
  }
}

resource sites_poc_refinity_invoicing_func_name_sites_poc_refinity_invoicing_func_name_hzb7htdfdvfwgbfc_canadacentral_01_azurewebsites_net 'Microsoft.Web/sites/hostNameBindings@2024-11-01' = {
  parent: sites_poc_refinity_invoicing_func_name_resource
  name: '${sites_poc_refinity_invoicing_func_name}-hzb7htdfdvfwgbfc.canadacentral-01.azurewebsites.net'
  location: 'Canada Central'
  properties: {
    siteName: 'poc-refinity-invoicing-func'
    hostNameType: 'Verified'
  }
}

resource sites_poc_refinity_invoicing_func_name_8fff9aa6_f850_4d58_8279_1809f7369877_POC_refinity_invoicing_func_conn_b0061e9d_7fac_4a8f_98d6_30eff2561146 'Microsoft.Web/sites/privateEndpointConnections@2024-11-01' = {
  parent: sites_poc_refinity_invoicing_func_name_resource
  name: '8fff9aa6-f850-4d58-8279-1809f7369877.POC_refinity_invoicing_func-conn-b0061e9d-7fac-4a8f-98d6-30eff2561146'
  location: 'Canada Central'
  properties: {
    privateEndpoint: {}
    privateLinkServiceConnectionState: {
      status: 'Approved'
      actionsRequired: 'None'
    }
    ipAddresses: [
      '10.250.0.7'
    ]
  }
}

resource sites_poc_refinity_invoicing_func_name_poc_Refinity_invoicing_PEP_8eeee179_42c1_4b0f_902d_68e443e0094e 'Microsoft.Web/sites/privateEndpointConnections@2024-11-01' = {
  parent: sites_poc_refinity_invoicing_func_name_resource
  name: 'poc-Refinity-invoicing-PEP-8eeee179-42c1-4b0f-902d-68e443e0094e'
  location: 'Canada Central'
  properties: {
    privateEndpoint: {}
    privateLinkServiceConnectionState: {
      status: 'Approved'
      actionsRequired: 'None'
    }
    ipAddresses: [
      '10.33.42.50'
    ]
  }
}

resource sites_poc_refinity_invoicing_func_name_b5bfcd3b_3929_4b8c_a4e5_08b9f380fe75_Dev_FunctionApp_Flex_Outbound 'Microsoft.Web/sites/virtualNetworkConnections@2024-11-01' = {
  parent: sites_poc_refinity_invoicing_func_name_resource
  name: 'b5bfcd3b-3929-4b8c-a4e5-08b9f380fe75_Dev-FunctionApp-Flex-Outbound'
  location: 'Canada Central'
  properties: {
    vnetResourceId: '${virtualNetworks_CA_Application_externalid}/subnets/Dev-FunctionApp-Flex-Outbound'
    isSwift: true
  }
}
